
// GENERATED CALCULATOR FOR CONVENIO: afa_553_09
// DO NOT EDIT MANUALLY - This file is generated by calculator-builder.js

function addRow(target, label, amount, qtyStr = "", formulaStr = "") {
  target.push({ label, amount, qtyStr, formulaStr });
}

function sumRows(rows) {
  return rows.reduce((sum, r) => sum + r.amount, 0);
}

module.exports = {
  getMetadata: () => {
    return [
      { id: "genPresentism", label: "Presentismo", type: "checkbox", defaultValue: true },
      { id: "genSeniority", label: "Antigüedad", type: "checkbox", defaultValue: true },
      { id: "genExtra50", label: "Horas extra 50%", type: "number", defaultValue: 0 },
      { id: "genExtra100", label: "Horas extra 100%", type: "number", defaultValue: 0 },
      { id: "concept_undefined", label: "Puntualidad", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Puntualidad no remunerativa", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Falla de caja principal", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Falla de caja auxiliar / cobradores", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Comision cobrador informada", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Movilidad / viaticos rendidos", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Cuota sindical UTEDYC afiliado 2,5%", type: "checkbox", defaultValue: true },
      { id: "concept_undefined", label: "Contribucion solidaria UTEDYC no afiliado 2%", type: "checkbox", defaultValue: true }
    ].filter(Boolean);
  },

  calculate: (ctx) => {
    const { inputs = {}, employee = {}, activeCatRow } = ctx;
    const salaryType = inputs.salaryType || "monthly";
    const workUnits = Number(inputs.workUnits || 0);
    const absentDays = Number(inputs.absentDays || 0);
    
    // Scale values
    const categoryMonthly = Number(activeCatRow?.valor || 0);
    const categoryDay = Number(activeCatRow?.valor_diario || categoryMonthly / 30);
    const categoryHourly = Number(activeCatRow?.valor_hora || categoryMonthly / 200);
    
    const monthDivisor = Number(ctx.rules?.dayDivisor || 30);
    const hourDivisor = Number(ctx.rules?.hourDivisor || 200);

    const rows = { remRows: [], nonRemRows: [], deductionRows: [], details: [] };
    
    // Base Salary
    let basic = 0;
    if (salaryType === "daily") {
      basic = categoryDay * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " jornales", categoryDay + " x " + workUnits);
    } else if (salaryType === "hourly") {
      basic = categoryHourly * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " horas", categoryHourly + " x " + workUnits);
    } else {
      basic = categoryMonthly;
      addRow(rows.remRows, "Basico", basic, "30 dias", categoryMonthly + " x 100%");
    }

    // Absences (Labor Law)
    const absenceDiscount = salaryType === "monthly" ? (basic / monthDivisor) * absentDays : categoryDay * absentDays;
    if (absentDays > 0) {
      addRow(rows.remRows, "Inasistencia injustificada", -absenceDiscount, absentDays + " dias", basic + " / " + monthDivisor + " x " + absentDays);
    }

    // Seniority
    let seniority = 0;
    const hasSeniority = inputs.genSeniority !== false && String(inputs.genSeniority) !== "false";
    if (hasSeniority) {
      const years = Math.min(employee.years || 0, 99);
      const pctPerYear = 2;
      seniority = basic * ((pctPerYear * years) / 100);
      if (seniority > 0) {
        addRow(rows.remRows, "Antiguedad", seniority, (pctPerYear * years) + "%", basic + " x " + pctPerYear + " x " + years + " / 100");
      }
    }

    // Presentism
    const hasPresentism = inputs.genPresentism !== false && String(inputs.genPresentism) !== "false";
    if (hasPresentism) {
      const pct = 15;
      const presentismFull = (basic + seniority) * (pct / 100);
      const requiresPerfect = true;
      
      if (requiresPerfect && absentDays > 0) {
        addRow(rows.details, "Presentismo", 0, "No corresponde por inasistencias");
      } else {
        addRow(rows.remRows, "Presentismo", presentismFull, pct + "%", (basic + seniority) + " x " + pct + " / 100");
      }
    }

    // Extra Hours
    const hourValue = (sumRows(rows.remRows) || basic) / hourDivisor;
    const extra50 = Number(inputs.genExtra50 || 0);
    const extra100 = Number(inputs.genExtra100 || 0);
    if (extra50 > 0) addRow(rows.remRows, "Horas extra 50%", hourValue * extra50 * 1.5, extra50 + " hs");
    if (extra100 > 0) addRow(rows.remRows, "Horas extra 100%", hourValue * extra100 * 2, extra100 + " hs");

    // Additional Concepts
    
    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 10 / 100);
      if (val !== 0) addRow(rows.remRows, "Puntualidad", val, "10%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 10 / 100);
      if (val !== 0) addRow(rows.remRows, "Puntualidad no remunerativa", val, "10%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 10 / 100);
      if (val !== 0) addRow(rows.remRows, "Falla de caja principal", val, "10%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 5 / 100);
      if (val !== 0) addRow(rows.remRows, "Falla de caja auxiliar / cobradores", val, "5%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) addRow(rows.remRows, "Comision cobrador informada", val, "0%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) addRow(rows.remRows, "Movilidad / viaticos rendidos", val, "0%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 2.5 / 100);
      if (val !== 0) addRow(rows.remRows, "Cuota sindical UTEDYC afiliado 2,5%", val, "2.5%");
    }
    

    if (inputs["concept_undefined"] !== false && String(inputs["concept_undefined"]) !== "false" && inputs["concept_undefined"] !== "0") {
      const val = (sumRows(rows.remRows) * 2 / 100);
      if (val !== 0) addRow(rows.remRows, "Contribucion solidaria UTEDYC no afiliado 2%", val, "2%");
    }
    

    // Deductions
    const remTotal = sumRows(rows.remRows);
    
    
    // Default Social Deductions
    addRow(rows.deductionRows, "Jubilacion", -(remTotal * 0.11), "11%");
    addRow(rows.deductionRows, "Ley 19.032 (PAMI)", -(remTotal * 0.03), "3%");
    addRow(rows.deductionRows, "Obra Social", -(remTotal * 0.03), "3%");

    return rows;
  }
};
