
// GENERATED CALCULATOR FOR CONVENIO: MAESTRANZA_Y_LIMPIEZA
// DO NOT EDIT MANUALLY - This file is generated by calculator-builder.js

function addRow(target, label, amount, qtyStr = "", formulaStr = "") {
  target.push({ label, amount, qtyStr, formulaStr });
}

function sumRows(rows) {
  return rows.reduce((sum, r) => sum + r.amount, 0);
}

module.exports = {
  getMetadata: () => {
    return [
      { id: "genPresentism", label: "Presentismo", type: "checkbox", defaultValue: true, detail: "Calculo: (Básico + Antigüedad) x 8.33%", group: "remunerative" },
      { id: "genSeniority", label: "Antigüedad", type: "checkbox", defaultValue: true, detail: "Calculo: Básico x 1% x Años", group: "remunerative" },
      { id: "genExtra50", label: "Horas extra 50%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 1.5 x Horas", group: "remunerative" },
      { id: "genExtra100", label: "Horas extra 100%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 2 x Horas", group: "remunerative" },
      { id: "concept_ADICIONAL_SALUD", label: "Adicional por tareas en ámbitos de salud", type: "checkbox", defaultValue: true, detail: "Realizar tareas en hospitales, sanatorios, clínicas, etc.<br><br><b>Calculo: sueldo basico x 12%</b>", group: "remunerative" },
      { id: "concept_VIATICO", label: "Viáticos (Régimen Seguridad Social)", type: "number", defaultValue: 0, detail: "Proporcional a días efectivamente trabajados<br><br><b>Calculo: Valor Unidad x Cantidad</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_EQUIPO", label: "Adicional por trabajo por equipo", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: sueldo basico x 13%</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_POR_TAREAS_EN_AMBITOS_DE_SALUD", label: "Adicional por tareas en ámbitos de salud", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 12%</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_POR_TRABAJO_POR_EQUIPO", label: "Adicional por trabajo por equipo", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 13%</b>", group: "remunerative" },
      { id: "concept_ASIG_INTEGRACION_SOCIAL", label: "Asignación Integración Social", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 0%</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_COORDINADOR_A", label: "Adicional Coordinador A", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 0%</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_COORDINADOR_B", label: "Adicional Coordinador B", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 0%</b>", group: "remunerative" },
      { id: "concept_ADICIONAL_COORDINADOR_C", label: "Adicional Coordinador C", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y jornada<br><br><b>Calculo: Sueldo Básico x 0%</b>", group: "remunerative" },
      { id: "concept_NO_REMUNERATIVO", label: "Asignación Extraordinaria No Remunerativa", type: "checkbox", defaultValue: true, detail: "Aplica segun categoria, periodo y vigencia de escala<br><br><b>Calculo: escala salarial x 0%</b>", group: "remunerative" }
      
    ].filter(Boolean);
  },

  calculate: (ctx) => {
    const { inputs = {}, employee = {}, activeCatRow } = ctx;
    const salaryType = inputs.salaryType || "monthly";
    const workUnits = Number(inputs.workUnits || 0);
    const absentDays = Number(inputs.absentDays || 0);
    
    // Scale values
    const categoryMonthly = Number(activeCatRow?.monthly || activeCatRow?.valor || 0);
    const categoryDay = Number(activeCatRow?.day || activeCatRow?.valor_diario || categoryMonthly / 30);
    const categoryHourly = Number(activeCatRow?.hourly || activeCatRow?.valor_hora || categoryMonthly / 200);
    
    const monthDivisor = Number(ctx.rules?.dayDivisor || 30);
    const hourDivisor = Number(ctx.rules?.hourDivisor || 200);

    const rows = { remRows: [], noRemRows: [], deductionRows: [], employerRows: [], details: [] };
    
    // Base Salary
    let basic = 0;
    if (salaryType === "daily") {
      basic = categoryDay * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " jornales", categoryDay + " x " + workUnits);
    } else if (salaryType === "hourly") {
      basic = categoryHourly * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " horas", categoryHourly + " x " + workUnits);
    } else {
      basic = categoryMonthly;
      addRow(rows.remRows, "Basico", basic, "30 dias", categoryMonthly + " x 100%");
    }

    // Absences (Labor Law)
    const absenceDiscount = salaryType === "monthly" ? (basic / monthDivisor) * absentDays : categoryDay * absentDays;
    if (absentDays > 0) {
      addRow(rows.remRows, "Inasistencia injustificada", -absenceDiscount, absentDays + " dias", basic + " / " + monthDivisor + " x " + absentDays);
    }

    // Seniority
    let seniority = 0;
    const hasSeniority = inputs.genSeniority !== false && String(inputs.genSeniority) !== "false";
    if (hasSeniority) {
      const years = Math.min(employee.years || 0, 99);
      const pctPerYear = 1;
      seniority = basic * ((pctPerYear * years) / 100);
      if (seniority > 0) {
        addRow(rows.remRows, "Antiguedad", seniority, (pctPerYear * years) + "%", basic + " x " + pctPerYear + " x " + years + " / 100");
      }
    }

    // Presentism
    const hasPresentism = inputs.genPresentism !== false && String(inputs.genPresentism) !== "false";
    if (hasPresentism) {
      const pct = 8.33;
      const presentismFull = (basic + seniority) * (pct / 100);
      const requiresPerfect = true;
      
      if (requiresPerfect && absentDays > 0) {
        addRow(rows.details, "Presentismo", 0, "No corresponde por inasistencias");
      } else {
        addRow(rows.remRows, "Presentismo", presentismFull, pct + "%", (basic + seniority) + " x " + pct + " / 100");
      }
    }

    // Extra Hours
    const hourValue = (sumRows(rows.remRows) || basic) / hourDivisor;
    const extra50 = Number(inputs.genExtra50 || 0);
    const extra100 = Number(inputs.genExtra100 || 0);
    if (extra50 > 0) addRow(rows.remRows, "Horas extra 50%", hourValue * extra50 * 1.5, extra50 + " hs");
    if (extra100 > 0) addRow(rows.remRows, "Horas extra 100%", hourValue * extra100 * 2, extra100 + " hs");

    // Additional Concepts
    
    if (inputs["concept_ADICIONAL_SALUD"] !== false && String(inputs["concept_ADICIONAL_SALUD"]) !== "false" && inputs["concept_ADICIONAL_SALUD"] !== "0") {
      const val = (sumRows(rows.remRows) * 12 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional por tareas en ámbitos de salud", val, "12%");
      }
    }
    

    if (inputs["concept_VIATICO"] !== false && String(inputs["concept_VIATICO"]) !== "false" && inputs["concept_VIATICO"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Viáticos (Régimen Seguridad Social)", val, "0%");
      }
    }
    

    if (inputs["concept_ADICIONAL_EQUIPO"] !== false && String(inputs["concept_ADICIONAL_EQUIPO"]) !== "false" && inputs["concept_ADICIONAL_EQUIPO"] !== "0") {
      const val = (sumRows(rows.remRows) * 13 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional por trabajo por equipo", val, "13%");
      }
    }
    

    if (inputs["concept_ADICIONAL_POR_TAREAS_EN_AMBITOS_DE_SALUD"] !== false && String(inputs["concept_ADICIONAL_POR_TAREAS_EN_AMBITOS_DE_SALUD"]) !== "false" && inputs["concept_ADICIONAL_POR_TAREAS_EN_AMBITOS_DE_SALUD"] !== "0") {
      const val = (sumRows(rows.remRows) * 12 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional por tareas en ámbitos de salud", val, "12%");
      }
    }
    

    if (inputs["concept_ADICIONAL_POR_TRABAJO_POR_EQUIPO"] !== false && String(inputs["concept_ADICIONAL_POR_TRABAJO_POR_EQUIPO"]) !== "false" && inputs["concept_ADICIONAL_POR_TRABAJO_POR_EQUIPO"] !== "0") {
      const val = (sumRows(rows.remRows) * 13 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional por trabajo por equipo", val, "13%");
      }
    }
    

    if (inputs["concept_ASIG_INTEGRACION_SOCIAL"] !== false && String(inputs["concept_ASIG_INTEGRACION_SOCIAL"]) !== "false" && inputs["concept_ASIG_INTEGRACION_SOCIAL"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Asignación Integración Social", val, "0%");
      }
    }
    

    if (inputs["concept_ADICIONAL_COORDINADOR_A"] !== false && String(inputs["concept_ADICIONAL_COORDINADOR_A"]) !== "false" && inputs["concept_ADICIONAL_COORDINADOR_A"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional Coordinador A", val, "0%");
      }
    }
    

    if (inputs["concept_ADICIONAL_COORDINADOR_B"] !== false && String(inputs["concept_ADICIONAL_COORDINADOR_B"]) !== "false" && inputs["concept_ADICIONAL_COORDINADOR_B"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional Coordinador B", val, "0%");
      }
    }
    

    if (inputs["concept_ADICIONAL_COORDINADOR_C"] !== false && String(inputs["concept_ADICIONAL_COORDINADOR_C"]) !== "false" && inputs["concept_ADICIONAL_COORDINADOR_C"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Adicional Coordinador C", val, "0%");
      }
    }
    

    if (inputs["concept_NO_REMUNERATIVO"] !== false && String(inputs["concept_NO_REMUNERATIVO"]) !== "false" && inputs["concept_NO_REMUNERATIVO"] !== "0") {
      const val = (sumRows(rows.remRows) * 0 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Asignación Extraordinaria No Remunerativa", val, "0%");
      }
    }
    

    // Deductions
    const remTotal = sumRows(rows.remRows);
    
    
    // Default Social Deductions
    addRow(rows.deductionRows, "Jubilacion", (remTotal * 0.11), "11%");
    addRow(rows.deductionRows, "Ley 19.032 (PAMI)", (remTotal * 0.03), "3%");
    addRow(rows.deductionRows, "Obra Social", (remTotal * 0.03), "3%");

    return rows;
  }
};
