
// GENERATED CALCULATOR FOR CONVENIO: Personal Mensualizado AFA - UTEDYC
// DO NOT EDIT MANUALLY - This file is generated by calculator-builder.js

function addRow(target, label, amount, qtyStr = "", formulaStr = "") {
  target.push({ label, amount, qtyStr, formulaStr });
}

function sumRows(rows) {
  return rows.reduce((sum, r) => sum + r.amount, 0);
}

module.exports = {
  getMetadata: () => {
    return [
      { id: "genPresentism", label: "Presentismo", type: "checkbox", defaultValue: true, detail: "Calculo: (Básico + Antigüedad) x 10%", group: "remunerative" },
      { id: "genSeniority", label: "Antigüedad", type: "checkbox", defaultValue: true, detail: "Calculo: Básico x 1% x Años", group: "remunerative" },
      { id: "genExtra50", label: "Horas extra 50%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 1.5 x Horas", group: "remunerative" },
      { id: "genExtra100", label: "Horas extra 100%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 2 x Horas", group: "remunerative" },
      { id: "gen_CASH_SHORTAGE_MAIN", label: "Falla de caja principal", type: "checkbox", defaultValue: true, detail: "Caja principal<br><br><b>Calculo: basic x 10%</b>", group: "remunerative" },
      { id: "gen_CASH_SHORTAGE_AUX", label: "Falla de caja auxiliar / cobradores", type: "checkbox", defaultValue: true, detail: "Caja auxiliar o cobradores<br><br><b>Calculo: basic x 5%</b>", group: "remunerative" },
      { id: "gen_SCHOLARSHIP_SUBSIDY", label: "Subsidio becas", type: "checkbox", defaultValue: true, detail: "10% por beca sobre Administrativo 4ta Auxiliar de Primera. Requiere validación manual del requisito de entidad.<br><br><b>Calculo: Sueldo Básico x 10%</b>", group: "remunerative" }
      
    ].filter(Boolean);
  },

  calculate: (ctx) => {
    const { inputs = {}, employee = {}, activeCatRow } = ctx;
    const salaryType = inputs.salaryType || "monthly";
    const workUnits = Number(inputs.workUnits || 0);
    const absentDays = Number(inputs.absentDays || 0);
    
    // Scale values
    const categoryMonthly = Number(activeCatRow?.monthly || activeCatRow?.valor || 0);
    const categoryDay = Number(activeCatRow?.day || activeCatRow?.valor_diario || categoryMonthly / 30);
    const categoryHourly = Number(activeCatRow?.hourly || activeCatRow?.valor_hora || categoryMonthly / 200);
    
    const monthDivisor = Number(ctx.rules?.dayDivisor || 30);
    const hourDivisor = Number(ctx.rules?.hourDivisor || 200);

    const rows = { remRows: [], noRemRows: [], deductionRows: [], employerRows: [], details: [] };
    
    // Base Salary
    let basic = 0;
    if (salaryType === "daily") {
      basic = categoryDay * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " jornales", categoryDay + " x " + workUnits);
    } else if (salaryType === "hourly") {
      basic = categoryHourly * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " horas", categoryHourly + " x " + workUnits);
    } else {
      basic = categoryMonthly;
      addRow(rows.remRows, "Basico", basic, "30 dias", categoryMonthly + " x 100%");
    }

    // Absences (Labor Law)
    const absenceDiscount = salaryType === "monthly" ? (basic / monthDivisor) * absentDays : categoryDay * absentDays;
    if (absentDays > 0) {
      addRow(rows.remRows, "Inasistencia injustificada", -absenceDiscount, absentDays + " dias", basic + " / " + monthDivisor + " x " + absentDays);
    }

    // Seniority
    let seniority = 0;
    const hasSeniority = inputs.genSeniority !== false && String(inputs.genSeniority) !== "false";
    if (hasSeniority) {
      const years = Math.min(employee.years || 0, 99);
      const pctPerYear = 1;
      seniority = basic * ((pctPerYear * years) / 100);
      if (seniority > 0) {
        addRow(rows.remRows, "Antiguedad", seniority, (pctPerYear * years) + "%", basic + " x " + pctPerYear + " x " + years + " / 100");
      }
    }

    // Presentism
    const hasPresentism = inputs.genPresentism !== false && String(inputs.genPresentism) !== "false";
    if (hasPresentism) {
      const pct = 10;
      const presentismFull = (basic + seniority) * (pct / 100);
      const requiresPerfect = true;
      
      if (requiresPerfect && absentDays > 0) {
        addRow(rows.details, "Presentismo", 0, "No corresponde por inasistencias");
      } else {
        addRow(rows.remRows, "Presentismo", presentismFull, pct + "%", (basic + seniority) + " x " + pct + " / 100");
      }
    }

    // Extra Hours
    const hourValue = (sumRows(rows.remRows) || basic) / hourDivisor;
    const extra50 = Number(inputs.genExtra50 || 0);
    const extra100 = Number(inputs.genExtra100 || 0);
    if (extra50 > 0) addRow(rows.remRows, "Horas extra 50%", hourValue * extra50 * 1.5, extra50 + " hs");
    if (extra100 > 0) addRow(rows.remRows, "Horas extra 100%", hourValue * extra100 * 2, extra100 + " hs");

    // Additional Concepts
    
    if (inputs["concept_CASH_SHORTAGE_MAIN"] !== false && String(inputs["concept_CASH_SHORTAGE_MAIN"]) !== "false" && inputs["concept_CASH_SHORTAGE_MAIN"] !== "0") {
      const val = (sumRows(rows.remRows) * 10 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Falla de caja principal", val, "10%");
      }
    }
    

    if (inputs["concept_CASH_SHORTAGE_AUX"] !== false && String(inputs["concept_CASH_SHORTAGE_AUX"]) !== "false" && inputs["concept_CASH_SHORTAGE_AUX"] !== "0") {
      const val = (sumRows(rows.remRows) * 5 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Falla de caja auxiliar / cobradores", val, "5%");
      }
    }
    

    if (inputs["concept_SCHOLARSHIP_SUBSIDY"] !== false && String(inputs["concept_SCHOLARSHIP_SUBSIDY"]) !== "false" && inputs["concept_SCHOLARSHIP_SUBSIDY"] !== "0") {
      const val = (sumRows(rows.remRows) * 10 / 100);
      if (val !== 0) {
        const isNoRem = false;
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "Subsidio becas", val, "10%");
      }
    }
    

    // Deductions
    const remTotal = sumRows(rows.remRows);
    
    
    // Default Social Deductions
    addRow(rows.deductionRows, "Jubilacion", (remTotal * 0.11), "11%");
    addRow(rows.deductionRows, "Ley 19.032 (PAMI)", (remTotal * 0.03), "3%");
    addRow(rows.deductionRows, "Obra Social", (remTotal * 0.03), "3%");

    return rows;
  }
};
