const fs = require('fs/promises');
const path = require('path');
const { SKIP_GENERATION_IDS } = require('./calculator-registry');

/**
 * Builds a JS calculator file for a given convention JSON
 */
async function buildCalculator(rawConvenio) {
  // Static conventions have dedicated calculation engines — don't override them
  if (SKIP_GENERATION_IDS.has(rawConvenio.id)) return;

  const { buildPayrollConvention } = require('./convenio-service');
  const convenio = buildPayrollConvention(rawConvenio, "");
  const model = convenio.liquidationModel || {};
  const rules = model.rules || convenio.rules || {};
  const cleanNorm = (str) => String(str || '').toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, '');

  const rawConcepts = [
    ...(model.concepts || []),
    ...(model.nonRemunerative || []),
    ...(convenio.concepts || [])
  ];

  if (convenio.additionals || model.additionals) {
    const addsSrc = convenio.additionals || model.additionals;
    const adds = Array.isArray(addsSrc) ? addsSrc : Object.values(addsSrc);
    adds.forEach(a => {
      if (!a) return;
      rawConcepts.push({
        id: a.id || a.label,
        label: a.label || a.id,
        rowType: (a.type === 'non_remunerative' || a.nonRemunerative) ? 'non_remunerative' : 'remunerative',
        calculation: a.percent ? 'percent' : (a.monthly || a.amount ? 'fixed' : 'scaleValue'),
        percent: a.percent,
        amount: a.monthly || a.amount
      });
    });
  }

  const seenConcepts = new Set();
  const concepts = [];
  rawConcepts.forEach(c => {
    if (!c) return;
    const key = cleanNorm(c.label || c.concepto || c.id);
    if (!key || seenConcepts.has(key)) return;
    seenConcepts.add(key);
    concepts.push(c);
  });

  const rawDeductions = [
    ...(model.deductions || []),
    ...(model.retentions || []),
    ...(model.employerContributions || [])
  ];

  if (convenio.deductions) {
    const deds = Array.isArray(convenio.deductions) ? convenio.deductions : Object.values(convenio.deductions);
    deds.forEach(d => {
      if (!d) return;
      rawDeductions.push({
        id: d.id || d.label,
        label: d.label || d.id,
        rowType: 'deduction',
        percent: d.percent,
        amount: d.amount
      });
    });
  }
  if (convenio.retentions) {
    const rets = Array.isArray(convenio.retentions) ? convenio.retentions : Object.values(convenio.retentions);
    rets.forEach(r => {
      if (!r) return;
      rawDeductions.push({
        id: r.id || r.label,
        label: r.label || r.id,
        rowType: 'deduction',
        percent: r.percent,
        amount: r.amount
      });
    });
  }

  const seenDeductions = new Set();
  const deductions = [];
  rawDeductions.forEach(d => {
    if (!d) return;
    const key = cleanNorm(d.label || d.concepto || d.id);
    if (!key || seenDeductions.has(key)) return;
    seenDeductions.add(key);
    deductions.push(d);
  });

  const presentismRule = rules.presentism || {};
  const seniorityRule = rules.seniority || {};

  let code = `
// GENERATED CALCULATOR FOR CONVENIO: ${convenio.id}
// DO NOT EDIT MANUALLY - This file is generated by calculator-builder.js

function addRow(target, label, amount, qtyStr = "", formulaStr = "") {
  target.push({ label, amount, qtyStr, formulaStr });
}

function sumRows(rows) {
  return rows.reduce((sum, r) => sum + r.amount, 0);
}

module.exports = {
  getMetadata: () => {
    return [
      ${presentismRule.enabled ? `{ id: "genPresentism", label: "Presentismo", type: "checkbox", defaultValue: true, detail: "Calculo: (Básico + Antigüedad) x ${presentismRule.percent || 8.33}%", group: "remunerative" },` : ''}
      ${seniorityRule.enabled !== false ? `{ id: "genSeniority", label: "Antigüedad", type: "checkbox", defaultValue: true, detail: "Calculo: Básico x ${seniorityRule.percent || 1}% x Años", group: "remunerative" },` : ''}
      { id: "genExtra50", label: "Horas extra 50%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 1.5 x Horas", group: "remunerative" },
      { id: "genExtra100", label: "Horas extra 100%", type: "number", defaultValue: 0, detail: "Calculo: Valor hora x 2 x Horas", group: "remunerative" },
      ${concepts.map(c => {
        let calcDesc = "";
        let inputType = "checkbox";
        
        if (c.calculation === 'amountPerUnit') {
          inputType = "number";
          calcDesc = `Calculo: Valor Unidad x Cantidad`;
        } else if (c.calculation === 'fixed' || c.calculationType === 'fixed_amount' || (c.amount && !c.percent)) {
          if (c.amount) {
            inputType = "checkbox";
            calcDesc = `Calculo: $${c.amount} (Fijo)`;
          } else {
            inputType = "number";
            calcDesc = `Calculo: Monto ingresado manualmente`;
          }
        } else if (c.percent && Number(c.percent) > 0) {
          inputType = "checkbox";
          const baseName = c.base && !String(c.base).includes('revision_manual') ? String(c.base).replace(/_/g, ' ') : 'Sueldo Básico';
          calcDesc = `Calculo: ${baseName} x ${c.percent}%`;
        } else {
          inputType = "number";
          calcDesc = `Calculo: Monto / valor según convenio o escala`;
        }
        
        const textDetail = (c.detail || c.description || '').replace(/"/g, '\\"').replace(/\n/g, ' ');
        const finalDetail = textDetail ? `${textDetail}<br><br><b>${calcDesc}</b>` : `<b>${calcDesc}</b>`;
        return `{ id: "gen_${c.id}", label: "${c.label || c.concepto}", type: "${inputType}", defaultValue: ${inputType === 'number' ? '0' : 'true'}, detail: "${finalDetail}", group: "${(c.rowType === 'non_remunerative' || c.rowType === 'no_remunerativo' || String(c.naturaleza).toLowerCase().includes('no rem')) ? 'non_remunerative' : 'remunerative'}" }`;
      }).join(',\n      ')}${deductions.length > 0 ? ',' : ''}
      ${deductions.map((d, i) => {
        const dId = d.id || ('ded_' + i);
        let calcDesc = d.percent ? `Calculo: Remunerativo x ${d.percent}%` : (d.amount ? `Calculo: Fijo $${d.amount}` : "Calculo: Manual");
        const textDetail = (d.detail || d.description || '').replace(/"/g, '\\"').replace(/\n/g, ' ');
        const finalDetail = textDetail ? `${textDetail}<br><br><b>${calcDesc}</b>` : `<b>${calcDesc}</b>`;
        const inputType = (d.percent || d.amount) ? 'checkbox' : 'number';
        return `{ id: "gen_${dId}", label: "${d.label || d.concepto}", type: "${inputType}", defaultValue: ${inputType === 'number' ? '0' : 'true'}, detail: "${finalDetail}", group: "deduction" }`;
      }).join(',\n      ')}
    ].filter(Boolean);
  },

  calculate: (ctx) => {
    const { inputs = {}, employee = {}, activeCatRow } = ctx;
    const salaryType = inputs.salaryType || "monthly";
    const workUnits = Number(inputs.workUnits || 0);
    const absentDays = Number(inputs.absentDays || 0);
    
    // Scale values
    const categoryMonthly = Number(activeCatRow?.monthly || activeCatRow?.valor || 0);
    const categoryDay = Number(activeCatRow?.day || activeCatRow?.valor_diario || categoryMonthly / 30);
    const categoryHourly = Number(activeCatRow?.hourly || activeCatRow?.valor_hora || categoryMonthly / 200);
    
    const monthDivisor = Number(ctx.rules?.dayDivisor || 30);
    const hourDivisor = Number(ctx.rules?.hourDivisor || 200);

    const rows = { remRows: [], noRemRows: [], deductionRows: [], employerRows: [], details: [] };
    
    // Base Salary
    let basic = 0;
    if (salaryType === "daily") {
      basic = categoryDay * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " jornales", categoryDay + " x " + workUnits);
    } else if (salaryType === "hourly") {
      basic = categoryHourly * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " horas", categoryHourly + " x " + workUnits);
    } else {
      basic = categoryMonthly;
      addRow(rows.remRows, "Basico", basic, "30 dias", categoryMonthly + " x 100%");
    }

    // Absences (Labor Law)
    const absenceDiscount = salaryType === "monthly" ? (basic / monthDivisor) * absentDays : categoryDay * absentDays;
    if (absentDays > 0) {
      addRow(rows.remRows, "Inasistencia injustificada", -absenceDiscount, absentDays + " dias", basic + " / " + monthDivisor + " x " + absentDays);
    }

    // Seniority
    let seniority = 0;
    const hasSeniority = inputs.genSeniority !== false && String(inputs.genSeniority) !== "false";
    if (hasSeniority) {
      const years = Math.min(employee.years || 0, ${seniorityRule.capYears || 99});
      const pctPerYear = ${seniorityRule.percentPerYear || 1};
      seniority = basic * ((pctPerYear * years) / 100);
      if (seniority > 0) {
        addRow(rows.remRows, "Antiguedad", seniority, (pctPerYear * years) + "%", basic + " x " + pctPerYear + " x " + years + " / 100");
      }
    }

    // Presentism
    const hasPresentism = inputs.genPresentism !== false && String(inputs.genPresentism) !== "false";
    if (hasPresentism) {
      const pct = ${presentismRule.percent || 8.33};
      const presentismFull = (basic + seniority) * (pct / 100);
      const requiresPerfect = ${presentismRule.requiresNoUnjustifiedAbsence !== false};
      
      if (requiresPerfect && absentDays > 0) {
        addRow(rows.details, "Presentismo", 0, "No corresponde por inasistencias");
      } else {
        addRow(rows.remRows, "Presentismo", presentismFull, pct + "%", (basic + seniority) + " x " + pct + " / 100");
      }
    }

    // Extra Hours
    const hourValue = (sumRows(rows.remRows) || basic) / hourDivisor;
    const extra50 = Number(inputs.genExtra50 || 0);
    const extra100 = Number(inputs.genExtra100 || 0);
    if (extra50 > 0) addRow(rows.remRows, "Horas extra 50%", hourValue * extra50 * 1.5, extra50 + " hs");
    if (extra100 > 0) addRow(rows.remRows, "Horas extra 100%", hourValue * extra100 * 2, extra100 + " hs");

    // Helper to read inputs with any prefix
    const readVal = (k) => inputs["gen_" + k] ?? inputs["concept_" + k] ?? inputs[k];
    const isAct = (k) => { const v = readVal(k); return v !== undefined && v !== false && String(v) !== "false" && String(v) !== "0" && String(v) !== ""; };

    // Additional Concepts
    ${concepts.map((c, i) => {
      const cId = c.id || ('c_' + i);
      const hasPct = c.percent && Number(c.percent) > 0;
      return `
    if (isAct("${cId}")) {
      const rawV = readVal("${cId}");
      const val = ${hasPct ? `(sumRows(rows.remRows) * ${c.percent} / 100)` : `(rawV === true || String(rawV) === "true" ? ${c.amount || 0} : Number(rawV || 0))`};
      if (val !== 0) {
        const isNoRem = ${(c.rowType === 'non_remunerative' || c.rowType === 'no_remunerativo' || String(c.naturaleza).toLowerCase().includes('no rem')) ? 'true' : 'false'};
        addRow(isNoRem ? rows.noRemRows : rows.remRows, "${c.label || c.concepto}", val, "${hasPct ? `${c.percent}%` : ''}");
      }
    }
    `;
    }).join('\n')}

    // Deductions
    const remTotal = sumRows(rows.remRows);
    ${deductions.map((d, i) => {
      const dId = d.id || ('ded_' + i);
      return `
    if (isAct("${dId}")) {
      const rawV = readVal("${dId}");
      const val = ${d.amount ? `(rawV === true || String(rawV) === "true" ? ${d.amount} : Number(rawV || 0))` : (d.percent ? `(remTotal * ${d.percent} / 100)` : `Number(rawV || 0)`)};
      addRow(rows.deductionRows, "${d.label || d.concepto}", val, "${d.percent ? d.percent + '%' : ''}");
    }
      `;
    }).join('\n')}
    
    // Default Social Deductions
    addRow(rows.deductionRows, "Jubilacion", (remTotal * 0.11), "11%");
    addRow(rows.deductionRows, "Ley 19.032 (PAMI)", (remTotal * 0.03), "3%");
    addRow(rows.deductionRows, "Obra Social", (remTotal * 0.03), "3%");

    return rows;
  }
};
`;

  const outputPath = path.join(__dirname, '..', 'calculators', `${convenio.id}.js`);
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, code, 'utf-8');
  return outputPath;
}

module.exports = { buildCalculator };
