const fs = require('fs/promises');
const path = require('path');
const { buildPayrollConvention } = require('./convenio-service');

/**
 * Builds a JS calculator file for a given convention JSON
 */
async function buildCalculator(rawConvenio) {
  const convenio = buildPayrollConvention(rawConvenio, "");
  const model = convenio.liquidationModel || {};
  const rules = model.rules || convenio.rules || {};
  const concepts = model.concepts || [];
  const deductions = model.deductions || [];
  const presentismRule = rules.presentism || {};
  const seniorityRule = rules.seniority || {};

  let code = `
// GENERATED CALCULATOR FOR CONVENIO: ${convenio.id}
// DO NOT EDIT MANUALLY - This file is generated by calculator-builder.js

function addRow(target, label, amount, qtyStr = "", formulaStr = "") {
  target.push({ label, amount, qtyStr, formulaStr });
}

function sumRows(rows) {
  return rows.reduce((sum, r) => sum + r.amount, 0);
}

module.exports = {
  getMetadata: () => {
    return [
      ${presentismRule.enabled ? `{ id: "genPresentism", label: "Presentismo", type: "checkbox", defaultValue: true },` : ''}
      ${seniorityRule.enabled !== false ? `{ id: "genSeniority", label: "Antigüedad", type: "checkbox", defaultValue: true },` : ''}
      { id: "genExtra50", label: "Horas extra 50%", type: "number", defaultValue: 0 },
      { id: "genExtra100", label: "Horas extra 100%", type: "number", defaultValue: 0 },
      ${concepts.map(c => `{ id: "concept_${c.id}", label: "${c.label || c.concepto}", type: "${c.calculationType === 'fixed_amount' ? 'number' : 'checkbox'}", defaultValue: ${c.calculationType === 'fixed_amount' ? '0' : 'true'} }`).join(',\n      ')}
    ].filter(Boolean);
  },

  calculate: (ctx) => {
    const { inputs = {}, employee = {}, activeCatRow } = ctx;
    const salaryType = inputs.salaryType || "monthly";
    const workUnits = Number(inputs.workUnits || 0);
    const absentDays = Number(inputs.absentDays || 0);
    
    // Scale values
    const categoryMonthly = Number(activeCatRow?.monthly || activeCatRow?.valor || 0);
    const categoryDay = Number(activeCatRow?.day || activeCatRow?.valor_diario || categoryMonthly / 30);
    const categoryHourly = Number(activeCatRow?.hourly || activeCatRow?.valor_hora || categoryMonthly / 200);
    
    const monthDivisor = Number(ctx.rules?.dayDivisor || 30);
    const hourDivisor = Number(ctx.rules?.hourDivisor || 200);

    const rows = { remRows: [], noRemRows: [], deductionRows: [], employerRows: [], details: [] };
    
    // Base Salary
    let basic = 0;
    if (salaryType === "daily") {
      basic = categoryDay * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " jornales", categoryDay + " x " + workUnits);
    } else if (salaryType === "hourly") {
      basic = categoryHourly * workUnits;
      addRow(rows.remRows, "Basico", basic, workUnits + " horas", categoryHourly + " x " + workUnits);
    } else {
      basic = categoryMonthly;
      addRow(rows.remRows, "Basico", basic, "30 dias", categoryMonthly + " x 100%");
    }

    // Absences (Labor Law)
    const absenceDiscount = salaryType === "monthly" ? (basic / monthDivisor) * absentDays : categoryDay * absentDays;
    if (absentDays > 0) {
      addRow(rows.remRows, "Inasistencia injustificada", -absenceDiscount, absentDays + " dias", basic + " / " + monthDivisor + " x " + absentDays);
    }

    // Seniority
    let seniority = 0;
    const hasSeniority = inputs.genSeniority !== false && String(inputs.genSeniority) !== "false";
    if (hasSeniority) {
      const years = Math.min(employee.years || 0, ${seniorityRule.capYears || 99});
      const pctPerYear = ${seniorityRule.percentPerYear || 1};
      seniority = basic * ((pctPerYear * years) / 100);
      if (seniority > 0) {
        addRow(rows.remRows, "Antiguedad", seniority, (pctPerYear * years) + "%", basic + " x " + pctPerYear + " x " + years + " / 100");
      }
    }

    // Presentism
    const hasPresentism = inputs.genPresentism !== false && String(inputs.genPresentism) !== "false";
    if (hasPresentism) {
      const pct = ${presentismRule.percent || 8.33};
      const presentismFull = (basic + seniority) * (pct / 100);
      const requiresPerfect = ${presentismRule.requiresNoUnjustifiedAbsence !== false};
      
      if (requiresPerfect && absentDays > 0) {
        addRow(rows.details, "Presentismo", 0, "No corresponde por inasistencias");
      } else {
        addRow(rows.remRows, "Presentismo", presentismFull, pct + "%", (basic + seniority) + " x " + pct + " / 100");
      }
    }

    // Extra Hours
    const hourValue = (sumRows(rows.remRows) || basic) / hourDivisor;
    const extra50 = Number(inputs.genExtra50 || 0);
    const extra100 = Number(inputs.genExtra100 || 0);
    if (extra50 > 0) addRow(rows.remRows, "Horas extra 50%", hourValue * extra50 * 1.5, extra50 + " hs");
    if (extra100 > 0) addRow(rows.remRows, "Horas extra 100%", hourValue * extra100 * 2, extra100 + " hs");

    // Additional Concepts
    ${concepts.map(c => `
    if (inputs["concept_${c.id}"] !== false && String(inputs["concept_${c.id}"]) !== "false" && inputs["concept_${c.id}"] !== "0") {
      const val = ${c.calculationType === 'fixed_amount' ? `Number(inputs["concept_${c.id}"] || 0)` : `(sumRows(rows.remRows) * ${c.percent || 0} / 100)`};
      if (val !== 0) addRow(rows.remRows, "${c.label || c.concepto}", val, "${c.calculationType === 'fixed_amount' ? '' : `${c.percent || 0}%`}");
    }
    `).join('\n')}

    // Deductions
    const remTotal = sumRows(rows.remRows);
    ${deductions.map(d => `
    addRow(rows.deductionRows, "${d.label || d.concepto}", (remTotal * ${d.percent || 0} / 100), "${d.percent || 0}%");
    `).join('\n')}
    
    // Default Social Deductions
    addRow(rows.deductionRows, "Jubilacion", (remTotal * 0.11), "11%");
    addRow(rows.deductionRows, "Ley 19.032 (PAMI)", (remTotal * 0.03), "3%");
    addRow(rows.deductionRows, "Obra Social", (remTotal * 0.03), "3%");

    return rows;
  }
};
`;

  const outputPath = path.join(__dirname, '..', 'calculators', `${convenio.id}.js`);
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, code, 'utf-8');
  return outputPath;
}

module.exports = { buildCalculator };
